version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws s3 mb s3://${STACK_NAME}-app-artifact --region ${REGION} || true
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket ${STACK_NAME}-app-artifact --output-template-file NewSamTemplate.yaml
  post_build:
    commands:
      - aws --region ${REGION} cloudformation deploy --template-file NewSamTemplate.yaml --stack-name ${STACK_NAME}
                                  --capabilities CAPABILITY_IAM
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
